---
title: "sql_md"
output: github_document
parent: sql
nav_order: 1
---

---
layout: default
title: SQL – Applied
parent: SQL
nav_order: 1
---

```{r setup, include=FALSE}
rm(list = ls(all = TRUE))
#knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  results = "asis"
)
options(knitr.table.format = "markdown")
```

```{r}
install.packages(
  setdiff(
    c("DBI", "duckdb", "nycflights13", "tidyverse", "here"),
    rownames(installed.packages())
  )
)
```

```{r}
library(here)
library(DBI)
library(duckdb)
library(nycflights13)
library(tidyverse)
```

```{r}
# GitHub raw link for the DuckDB database file
url <- "https://github.com/AU-datascience/data/raw/main/413-613/flights.duckdb"

# Local path to save the file
dest <- here("sql", "flights.duckdb")

# Download the file
download.file(url, dest, mode = "wb")
```

```{r}
con <- dbConnect(duckdb(dbdir = "./flights.duckdb"))
class(con)
#dbDisconnect(con_p)
```

```{sql, connection=con, eval=FALSE}
#| label: lst-show-tables
  SHOW TABLES;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SHOW TABLES;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| label: lst-des-tables
  DESCRIBE;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  DESCRIBE;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  DESCRIBE airlines;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  DESCRIBE airlines;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
#| label: lst-select-planes
  SELECT tailnum, year, model
  FROM planes
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT tailnum, year, model
  FROM planes
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
#| label: lst-select-planes-2
  SELECT *
  FROM planes
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT *
  FROM planes
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT DISTINCT dest
  FROM flights
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT DISTINCT dest
  FROM flights
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT flight, distance, origin, dest
  FROM flights
  WHERE "distance" < 50;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT flight, distance, origin, dest
  FROM flights
  WHERE distance < 50;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT flight, month
  FROM flights
  WHERE "month" = 12
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT flight, month
  FROM flights
  WHERE month = 12
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT flight, origin
  FROM flights
  WHERE "origin" = 'JFK'
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT flight, origin
  FROM flights
  WHERE origin = 'JFK'
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT flight, origin, dest
  FROM flights
  WHERE "origin" = 'JFK' AND "dest" = 'CMH'
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT flight, origin, dest
  FROM flights
  WHERE origin = 'JFK' AND dest = 'CMH'
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT
      DISTINCT flight,
      origin,
      dest
  FROM
      flights
  WHERE
      NOT (origin = 'JFK'
          OR origin = 'LGA')
      AND dest = 'CMH'
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT
      DISTINCT flight,
      origin,
      dest
  FROM
      flights
  WHERE
      NOT (origin = 'JFK'
          OR origin = 'LGA')
      AND dest = 'CMH'
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT DISTINCT
      flight,
      origin,
      dest
  FROM flights
  WHERE
      origin NOT IN ('JFK', 'LGA')
      AND dest IN ('BWI', 'IAD', 'DCA')
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT DISTINCT
      flight,
      origin,
      dest
  FROM flights
  WHERE
      origin NOT IN ('JFK', 'LGA')
      AND dest IN ('BWI', 'IAD', 'DCA')
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT flight, dep_delay
  FROM flights
  WHERE dep_delay IS NOT NULL
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT flight, dep_delay
  FROM flights
  WHERE dep_delay IS NOT NULL
  LIMIT 5;
")
knitr::kable(res)
```

```{sql, connection=con, eval=FALSE}
#| connection: con
  SELECT flight, dep_delay
  FROM flights
  WHERE dep_delay IS NULL
  LIMIT 5;
```

```{r, echo=FALSE}
res <- dbGetQuery(con, "
  SELECT flight, dep_delay
  FROM flights
  WHERE dep_delay IS NULL
  LIMIT 5;
")
knitr::kable(res)
```



